spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    hikari:
      jdbc-url: jdbc:h2:mem:Morpheus;DB_CLOSE_ON_EXIT=FALSE

mqttServer:
  certificate:
    caCertificate: /home/hugo/Documents/TCC/mqtt_certificates/ca.crt
    serverCertificate: /home/hugo/Documents/TCC/mqtt_certificates/morpheus/morpheus.der
    serverKey: /home/hugo/Documents/TCC/mqtt_certificates/morpheus/morpheus.key
  configuration:
    id: morpheus-localServer
    host: 138.197.83.143
    port: 8883

morpheus:
  configuration:
    keepAlive: 10000
    serialNumber: adf654wae84fea5d8ea6
    password: 123456789
    directory: /home/hugo/Documents/TCC/configuration
    backup:
      numberOfResendTries: 5
      directory: /home/hugo/Documents/TCC/morpheusMessageBackup
      persistEvery: 20000
      fileName: backupMessages.txt
    messages:
      discardOldMessages: true
      discardMessagesAfter: 60

cloud:
  protocol: https
  host: hedwig-cloud.ml
  port: 443

api:
  host: 138.197.83.143
  port: 3000
  endpoint:
    configuration: configuration
    confirmation: confirmation
    data_transmission: data_transmission