spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    hikari:
      jdbc-url: jdbc:h2:mem:Morpheus;DB_CLOSE_ON_EXIT=FALSE

mqttServer:
  certificate:
    caCertificate: /home/hugo/Documents/TCC/morpheus/src/main/resources/certificates/ca.crt
    serverCertificate: /home/hugo/Documents/TCC/morpheus/src/main/resources/certificates/device001.der
    serverKey: /home/hugo/Documents/TCC/morpheus/src/main/resources/certificates/device001.key
  configuration:
    id: morpheus-localServer
    name: localhost
    port: 8883

morpheus:
  configuration:
    keepAlive: 600000
    serialNumber: adf654wae84fea5d8ea6

api:
  host: 138.197.83.143
  port: 3000
  endpoint:
    configuration: configuration
    confirmation: confirmation
    data_transmission: data_transmission